### ISSUE TITLE
Error on setting graph layout

### ISSUE THREAD

**Issue by gooney47** [jimmybow/mydcc#7]
I'm using the mydcc.Relayout to set the layout of a graph without redrawing it. Upon switching from dash 1.4.1 to 1.5.0 I get an error when I want to update the layout which leads to the layout not being updated at all. On dash 1.4.1 it still works fine. You can find the error below:

```
DOM element provided is null or undefined
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
Error: DOM element provided is null or undefined

    at Object.getGraphDiv (http://localhost:50300/_dash-component-suites/dash_core_components/async~plotlyjs.v1_4_0m1572364822.js:1:2161293)

    at Object.q [as relayout] (http://localhost:50300/_dash-component-suites/dash_core_components/async~plotlyjs.v1_4_0m1572364822.js:1:2232276)

    at t.value (http://localhost:50300/_dash-component-suites/mydcc/bundle.v0_1_22m1571909727.js:1:10432)

    at finishClassComponent (http://localhost:50300/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1572367177.8.6.js:14876:31)

    at updateClassComponent (http://localhost:50300/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1572367177.8.6.js:14831:24)

    at beginWork (http://localhost:50300/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1572367177.8.6.js:15779:16)

    at performUnitOfWork (http://localhost:50300/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1572367177.8.6.js:19447:12)

    at workLoop (http://localhost:50300/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1572367177.8.6.js:19487:24)

    at renderRoot (http://localhost:50300/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1572367177.8.6.js:19570:7)

    at performWorkOnRoot (http://localhost:50300/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1572367177.8.6.js:20477:7)
```

**Comment by jimmybow** [comment]
Thanks for your reply. I will see what's changed in Dash 1.5.0.

**Comment by gooney47** [comment]
I made a small example that works when using 1.4.1 but sometimes(!) doesn't work with 1.5.0 (and higher). I mainly copied it from the relayout example in your documentation.

```
# -*- coding: utf-8 -*-
import dash
import dash_core_components as dcc
import dash_html_components as html
from  dash.dependencies import Output, Input
import mydcc

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    mydcc.Relayout( id = "rrr", aim = 'graph' ),
    dcc.Graph( id = 'graph',
               figure = { 'data': [  {'x': [1, 2, 3], 'y': [4, 1, 2]}  ]  }
              ),
    dcc.Input(id = 'in',
              placeholder = 'Enter a title ...',
              type = 'text',
              value = ''
              )
])

@app.callback(
    Output('rrr', 'layout'),
    [Input('in', 'value')])
def myfun(x):
    return {'title':x}

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by n0mer** [comment]
@jimmybow any luck?

**Comment by wahid18benz** [comment]
@jimmybow Please,Any Update for this issue !?
I'm trying to update annotation text based on selectedData is that possible ?

**Comment by jimmybow** [comment]
I don't know how to fix this problem.
The problem is on javascript function **Plotly.relayout**, it can't work on the plotly graph from **dcc.Graph**.

**Comment by gooney47** [comment]
@jimmybow I made it work with dash 1.5 by loading the plotly div in the render function right before the relayout call. But trying to make it work with dash 1.12 (latest) wasnt possible. We might suffer same probleme as here: https://community.plotly.com/t/typeerror-e-is-undefined-when-using-plotly-relayout-followed-by-plotly-purge/20442 and this is still unfixed. I will try to make a minimal example an make new issue in plotly repo but I might not be able to make one up...

**Comment by injoum** [comment]
Any updates on the issue? since I am suffering from old Dash bugs and I need it to work with the new Dash versions I am getting a bit desparate.

**Comment by vivienmast** [comment]
Not sure if this is the same, but on using the Relayout component in the minimal example provided, I get this error, and the component doesn't update:

```
ReferenceError: Plotly is not defined
    at t.value (bundle.v0_1_22m1642070620.js:1)
    at Ie (react-dom@16.v1_21_0m1636373583.14.0.min.js:104)
    at rh (react-dom@16.v1_21_0m1636373583.14.0.min.js:103)
    at zj (react-dom@16.v1_21_0m1636373583.14.0.min.js:228)
    at Th (react-dom@16.v1_21_0m1636373583.14.0.min.js:152)
    at tj (react-dom@16.v1_21_0m1636373583.14.0.min.js:152)
    at Te (react-dom@16.v1_21_0m1636373583.14.0.min.js:146)
    at react-dom@16.v1_21_0m1636373583.14.0.min.js:61
    at unstable_runWithPriority (react@16.v1_21_0m1636373583.14.0.min.js:25)
    at Da (react-dom@16.v1_21_0m1636373583.14.0.min.js:60)
```
